### ISSUE TITLE
Define interface for eosfilestore

### ISSUE THREAD

**Issue by bachvtuan** [grigio/eosfilestore#1]
I see you used action 'transfer' with minimal amount is 0.0001 EOS that is small cost. We can reduce to zero cost by define interface like decentwitter or eosproof1111 do.
This is example cpp in decentwitter https://github.com/kesar/decentwitter/blob/master/decentwitter/decentwitter.cpp
So user just cost CPU and Bandwidth and they can recover after 1 day so basically this is free .

**Comment by grigio** [comment]
Currently `eosfilestore` isn't a smart contract and normal txs are used which have 256 chars limitation in memo. Actually using an `action` instead of `transfer` seems more flexible.

**Comment by bachvtuan** [comment]
yeah. you can upload file and download file with shorter time because no longer 256 chars limitation in transfer also you can add other params as well.

**Comment by grigio** [comment]
ok it works in testnet, but I can't pay for 50kb RAM https://eospark.com/Jungle/account/eosfilestor1

**Comment by bachvtuan** [comment]
That bad. Too much cost for simple smart contract.

**Comment by grigio** [comment]
Decentwitter is 62k, the plan b is to use decentwitter as storage :p

**Comment by bachvtuan** [comment]
Please don't  do that otherwise community will hate us because unreadable tweets :)
Let see after side chain is applied the ram market will go down and you may have a chance.

**Comment by bachvtuan** [comment]
Btw I think you can use avatar action is good option that will not affect list of tweets.

**Comment by grigio** [comment]
it works with avatar :D, great suggestion! Tomorrow I'll clean up the code and I'll publish a new release

**Comment by grigio** [comment]
fixed in v0.0.27
