### ISSUE TITLE
Add compress option when upload file

### ISSUE THREAD

**Issue by bachvtuan** [grigio/eosfilestore#2]
It is really useful if you upload text file and compress it will save a lot of bandwidth.
The ratio can reach up to 10:1

**Comment by bachvtuan** [comment]
Also add password option also good and keep their files safe :)

**Comment by grigio** [comment]
Do you mean compress the file or compress the transaction? I think the user can encrypt the file before the upload

**Comment by bachvtuan** [comment]
I AGREE, we shouldn't make tool more complicated so closed.
