### ISSUE TITLE
maxPayloadSize too small

### ISSUE THREAD

**Issue by bachvtuan** [grigio/eosfilestore#3]
https://eosflare.io/tx/6fe3fc5240869b6007a666b74e2ea310931e608b46d8cc9817cb8be9ae480529
This is the timestamp I tried with http://eosproof.io/
You can see I put in the memo with a lot of text and I think you can increase maxPayloadSize to speed up upload and download file process because it take less transactions to process.

**Comment by grigio** [comment]
fixed in v0.0.27
