### ISSUE TITLE
Add an explanation to how it works

### ISSUE THREAD

**Issue by MrToph** [grigio/eosfilestore#5]
Hi,
I was excited and wanted to know how it works.

I had to dig in the code to find out and then was a bit disappointed:
It's just base64 encoding the file and sending it as messages to `decentwitter`

Not to lower your effort or anything, but maybe add it to the README that this does not use IPFS (which is mentioned a lot when talking about EOS and file storage)?

**Comment by grigio** [comment]
Yes, IPFS do not guarantee that a file will be stored in the future
